services:
  blog-app:
    build: .
    container_name: node-blog
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app:Z
      - /app/node_modules
    networks:
      - web-net
    restart: always
    healthcheck:
      # Use Node.js to make a request instead of curl
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => { if (r.statusCode !== 200) throw new Error(r.statusCode) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-connector
    networks:
      - web-net
    restart: always
    command: tunnel run --token ${TUNNEL_TOKEN} --protocol http2 --url http://blog-app:${PORT}
    # No need to list the token here anymore! 
    # Docker Compose automatically looks for a .env file.

networks:
  web-net:
    driver: bridge