apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-credentials
type: Opaque
data:
  TUNNEL_TOKEN: ZXlKaElqb2lNVEEwWkRrek1qa3laV1JqTURGa01HVm1OelU0T0dVek1UYzBPVE0wTjJJaUxDSjBJam9pTjJNeU1HUmlNVGt0T1RNMU1pMDBaREU1TFRsbE1qRXRPVEZsTUdOaVl6ZG1ZV0U1SWl3aWN5STZJbHBFV1hkT01sVXpXV3BSZEUxVVp6Sk5RekF3VGtkRmQweFhTVFJaVkVWMFdrUnJNazlFUW14WmFteG9UMFJvYXlKOQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: blog-app-secrets
type: Opaque
data:
  ADMIN_PASSWORD: "U3Vja015QkBsbHMh"